# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QzFi_R98828kVk2DHdzpVXksxyrqFFBT
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

uri = 'https://raw.githubusercontent.com/wcota/covid19br/master/cases-brazil-cities.csv'
dcovid = pd.read_csv(uri)
dcovid.columns = ['país','estado','cidade','ibgeID','mortes','total_de_Casos','mortes_por_100_mil_habitantes','total_de_Casos_por_100_mil_habitantes','mortes_por_total_de_casos','fonte','data','novos_Casos','novas_Mortes','última_data_de_informação']
maior_casos = dcovid['total_de_Casos'].max()
menor_casos = dcovid['total_de_Casos'].min()
maior_morte_covid = dcovid['mortes'].max()
menor_morte_covid = dcovid['mortes'].min()
estado_5maior_mortes = dcovid.nlargest(5,'mortes',keep='first')
estado_5menor_mortes = dcovid.nsmallest(5,'mortes')
total_casos_brasil = dcovid.loc[dcovid['país'] == 'Brazil','total_de_Casos'].sum()
total_mortes_brasil = dcovid.loc[dcovid['país'] == 'Brazil','mortes'].sum()
print('Cidade com maior numero de casos eh:',dcovid.loc[dcovid['total_de_Casos'] == maior_casos,'cidade'])
print('Cidade com menor numero de casos eh:',dcovid.loc[dcovid['total_de_Casos'] == menor_casos,'cidade'])
print('Estado com maior numero de casos eh:',dcovid.loc[dcovid['total_de_Casos'] == maior_casos,'estado'])
print('Estado com menor numero de casos eh:',dcovid.loc[dcovid['total_de_Casos'] == menor_casos,'estado'])
print('Cidade com maior numero de mortes eh:',dcovid.loc[dcovid['mortes'] == maior_morte_covid,'cidade'])
print('Cidade com menor numero de mortes eh:',dcovid.loc[dcovid['mortes'] == menor_morte_covid,'cidade'])
print('Estado com maior numero de mortes eh:',dcovid.loc[dcovid['mortes'] == maior_morte_covid,'estado'])
print('Estado com menor numero de mortes eh:',dcovid.loc[dcovid['mortes'] == menor_morte_covid,'estado'])
print('Total de casos de covid no brasil:', total_casos_brasil)
print('Total de mortes por covid no brasil:', total_mortes_brasil)

plt.subplot(1,2,1)
sns.barplot(x ='estado',y='mortes', data = estado_5maior_mortes)
plt.subplot(1,2,2)
sns.histplot(x ='estado',y='mortes',data = estado_5menor_mortes)